.github/PULL_REQUEST_TEMPLATE.md
.gitignore
LICENSE
README.md

We need to add some boilerplate to the new repo.
https://mitlibraries.atlassian.net/browse/RDI-67
* Adds PR template.
* Updates gitignore.
* Adds MIT Libraries to license.
* Links to TIMDEX in readme.
More changes to the gitignore may be needed in future depending
on what we end up using.

Initial repo setup

---

.github/workflows/mit-libraries-ruby-ci.yml
.gitignore
Gemfile
Gemfile.lock
test/test_helper.rb

This attempts to follow the instructions from https://github.com/MITLibraries/actions-workflows for this repository:
- Adds the workflow from the Actions screen, looking for workflows from the MIT Libraries
- Appends to that commit with the instructions from the linked repository above. 
NO
YES

Add starter workflow

---

Gemfile
Gemfile.lock
README.md
app/models/query_builder.rb
app/models/timdex_wrapper.rb
test/models/query_builder_test.rb
test/models/timdex_wrapper_test.rb
test/test_helper.rb
test/vcr_cassettes/timdex_404.yml
test/vcr_cassettes/timdex_multiword.yml
test/vcr_cassettes/timdex_popcorn.yml
test/vcr_cassettes/timdex_quoted.yml

* We need a wrapper model for the Timdex API in order to easily send and
process searches against it.
* We also need a separate query builder which can support future
expansion.
* https://github.com/MITLibraries/timdex-ui/issues/18
* https://github.com/MITLibraries/timdex-ui/issues/19
* This builds a TimdexWrapper model with a single public method, search.
There are private methods for reading the two environment variables,
as well as for extending the TIMDEX_BASE value to the specific search
endpoint (using the result of the query builder)
* I've chosen to use private methods for all of these as I don't think
the rest of the application will need to interact with those tools
separately? This may not end up being the case, in which case they can
be made public (and have tests written for …

First steps toward Query Wrapper

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_facets.scss
app/controllers/basic_search_controller.rb
app/models/query_builder.rb
app/models/timdex_wrapper.rb
app/views/basic_search/_facet.html.erb
app/views/basic_search/_facet_empty.html.erb
app/views/basic_search/_result.html.erb
app/views/basic_search/_result_empty.html.erb
app/views/basic_search/results.html.erb
test/controllers/basic_search_controller_test.rb
test/models/timdex_wrapper_test.rb
test/vcr_cassettes/timdex_404.yml
test/vcr_cassettes/timdex_hallo.yml
test/vcr_cassettes/timdex_no_results.yml

This refactors the QueryBuilder and TimdexWrapper for cleaner application flow (first commit) and then surfaces the returned results and facets in the UI (second commit).
This should close #21 when it merges.
NO
YES - adding byebug for debugging in test/dev

Initial surfacing of results and facets in the UI

---

.gitignore
app/models/enhancer.rb
app/models/enhancer_patterns.rb
test/models/enhancer_patterns_test.rb
test/models/enhancer_test.rb

* We want an way to detect intent from user input and believe analyzing
the raw input in various ways and categorizing what we know about it
will be helpful in both building up queries to our search indexes but
also in detecting when something other than a search index may be
helpful
* https://github.com/MITLibraries/timdex-ui/issues/20
* Creates an Enhancer class and EnhancerPatterns class with two initial
examples (ISBN and ISSN detection)
- this is not yet connected to the user input stage or query builder
stage as there is work underway already that this will somewhat
conflict with so we'll need to wire it up when it up separately
[our …

Adds initial Enhancer class and two examples

---

Gemfile
Gemfile.lock
app/controllers/basic_search_controller.rb
app/models/enhancer_patterns.rb
app/models/query_builder.rb
app/views/basic_search/_isbn.html.erb
app/views/basic_search/_issn.html.erb
app/views/basic_search/results.html.erb
test/controllers/basic_search_controller_test.rb
test/models/enhancer_patterns_test.rb
test/models/query_builder_test.rb
test/vcr_cassettes/timdex_1234-5678.yml
test/vcr_cassettes/timdex_9781509053278.yml

* The initial implementation of QueryBuilder and Enhancer was done in
parallel. This brings that work together.
https://github.com/MITLibraries/timdex-ui/issues/30
* Add Enhancer to the BasicSearch controller
* Refactors QueryBuilder to use Enhancer instead of Params as input
* Displays example fact cards for ISSN/ISBN
* QueryBuilder doesn't do anything interesting with the Enhancer data
that is passed in yet
* The ISSN/ISBN fact cards are not useful yet. If we don't have anything
interesting to do with these detected Facts, we'll stop displaying
them but for now it is nice to have an example so we can start
thinking about what Facts we can detect and what …

Adds Enhancers to Basic Search flow

---

app/views/layouts/_head.html.erb

This came about because of an uncaught syntax error in the browser
console regarding our import statements in application.js. We
suspected that this error indicated that we were not loading
Hotwire/Turbo properly.
https://mitlibraries.atlassian.net/browse/RDI-75
This overwrites the mitlibraries-theme template in order to add the
JS importmap tags required for importmap to load our JS properly.
* The error that flagged us to this problem persists, but it seems
innocuous as our JS still loads and Turbo frames work as expected.
* In addition to the `javascript_importmap_tags` method, the custom
template includes `csrf_meta_tags`, `csp_meta_tag`, and
`stylesheet_link_tag`, all of which are included in the default
Rails 7 template and seem harmless to add.
* I removed a couple of comments from …

Add importmap tags to head

---

app/controllers/record_controller.rb
app/helpers/record_helper.rb
app/models/timdex_wrapper.rb
app/views/basic_search/_result.html.erb
app/views/record/view.html.erb
config/environments/test.rb
config/routes.rb
db/schema.rb
test/controllers/basic_search_controller_test.rb
test/controllers/record_controller_test.rb
test/helpers/record_helper_test.rb
test/models/timdex_wrapper_test.rb
test/test_helper.rb
test/vcr_cassettes/timdex_record_no_record.yml
test/vcr_cassettes/timdex_record_sample.yml

* A lot of fields are now being provided by the API, and those fields
should be included in the UI.
* https://mitlibraries.atlassian.net/browse/RDI-81
* Defines a full record view, because the list of search results is not
the place to dislay dozens of metadata fields for a single record.
* This full record view then makes use of a number of helper methods,
each of which are focused on a specific type of data (strings, lists,
hashes, and a specific format of hash with "kind" and "value"
sub-properties.
* These primary helpers in turn make use of internal methods, but being
internal they are not explicitly and separately tested.
* CodeClimate is flagging repeated code between the `search` and `record` methods in the Timdex wrapper, probably because they are very copy-pasta. There's …

First work towards full record display

---

app/controllers/basic_search_controller.rb
app/controllers/record_controller.rb
app/models/timdex_base.rb
app/models/timdex_record.rb
app/models/timdex_search.rb
test/controllers/basic_search_controller_test.rb
test/models/timdex_test.rb
test/vcr_cassettes/data.yml
test/vcr_cassettes/timdex_1234-5678.yml
test/vcr_cassettes/timdex_9781509053278.yml
test/vcr_cassettes/timdex_empty_search.yml
test/vcr_cassettes/timdex_hallo.yml
test/vcr_cassettes/timdex_no_results.yml
test/vcr_cassettes/timdex_null_search.yml
test/vcr_cassettes/timdex_record_no_record.yml
test/vcr_cassettes/timdex_record_null_record.yml
test/vcr_cassettes/timdex_record_sample.yml

* The timdex model was handling interactions for both search and
retrieve, which are separate interactions that don't intersect other
than the client setup
* https://mitlibraries.atlassian.net/browse/RDI-118
* The shared timdex graphql client logic is moved to a timdex_base class
and timdex_search and timdex_record are created.
Side Effects:
There may be some confusion calling the new model `timdex_record` rather than `timdex_retrieve`. However, other parts of this app are already referring to a single record retrieval as `record` and not `retrieve` so for now I think this is the correct name.
all issues introduced by these …

Refactor TIMDEX models

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_results.scss
app/views/search/_result.html.erb
app/views/search/results.html.erb

This work was prompted by the initial set of UI iterations.
https://mitlibraries.atlassian.net/browse/RDI-99
This proposes a path for the results UI design, focused on the
minimal information needed to identify whether a resource is useful.
Since we will have a full record view, these brief results include
only title, content type, publication date, contributors, and
full-text link. Unlike Bento, they do not include subjects, as I
couldn't discern a use case for this in the brief results. (More on
this in the ticket if you're curious.)
This makes some improvements to a11y, including highlighting
links and adding `:visited` classes. The colors of these are
subject to change; I'm specifically interested in the
reviewer's opinion of the green used for the 'View online' button;
this is …

Initial refinements to search results UI

---

app/models/fact_doi.rb
app/views/fact/doi.html.erb
test/controllers/fact_controller_test.rb
test/vcr_cassettes/fact_doi_10_1038_nphys1170.yml
test/vcr_cassettes/fact_doi_10_1126_sciadv_abj1076.yml
test/vcr_cassettes/fact_doi_10_3207_2959859860.yml

* Useful actions in the Fact panel are a large part of the intent of
fact panels
* https://mitlibraries.atlassian.net/browse/RDI-130
* Uses unpaywall instead of crossref to get more information about
open availability
* Provides a link to an Open Access copy if one is available
* Always provides a link to Primo/Alma link resolver to check MIT access
* the html/css needs work, but as we want to normalize these fact
panels I felt we could address that later
issues (link to those issues in the Pull Request details …

Adds actionable links to DOI fact panel

---

app/helpers/record_helper.rb
app/views/fact/doi.html.erb
app/views/record/_misc.html.erb
app/views/record/_record.html.erb
app/views/record/_sidebar.html.erb
app/views/record/view.html.erb
app/views/search/_form.html.erb
test/controllers/record_controller_test.rb
test/helpers/record_helper_test.rb

* Our initial implementation focused on getting the information on the
page. This takes a first pass at organization the information.
* https://mitlibraries.atlassian.net/browse/RDI-138
* implemented a general organization of data by looking back at some
full record views we had made in Bento, and combining that with a look
at the data available in TIMDEX, and then making some initial
decisions on how to display the data
* several fields coming back from TIMDEX are still not fully integrated
into the page and are instead left at the end.
* DSpace and Woods Hole sources were added to the advanced form filter
* Many data fields still need additional work or …

Updates to full record view

---

README.md
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_global_alerts.scss

Note: The PR build has a `GLOBAL_ALERT` set to make reviewing this easier. You can also set one locally, or change it in the PR build to see these changes.
* The global alert in our theme gem expects some alert classes to be the
version in the gem. However, timdex-ui overrides those styles. Until
we merge these new styles back to the theme gem, we need to also
override a bit of the global alert.
* https://mitlibraries.atlassian.net/browse/RDI-207
* Adds a global_alerts scss partial and styles to support global alerts
* Documents in README that `GLOBAL_ALERT` comes from the theme gem
* Adds documentation in README for `TIMDEX_SOURCES` which were
introduced …

Adds timdex-ui styles for global alert

---

Gemfile.lock
README.md
app/assets/stylesheets/partials/_search.scss
app/views/basic_search/index.html.erb
app/views/static/_about.html.erb

We want to provide users with information about the app. This
should be easily configurable, as we are configuring multiple experimental
interfaces under different URLs.
https://mitlibraries.atlassian.net/browse/RDI-213
This adds an 'about' partial that renders the content of the
environment variable `ABOUT_APP`.
* Storing context about the app in env is a bit messy, but it seems to
be the best approach here.
* A new platform (`x86_64-darwin-21`) was added to Gemfile.lock as a
result of running `bundle install`. Documenting here in case it causes
problems.
(not just this pull …

Add context about application

---

app/views/search/_form.html.erb

In the advanced search form, the name attribute for fundingInformation
is incorrectly "Funding information". This passes the wrong field name
to params and causes all fundingInformation searches originating from
the search form to fail.
N/A.
This updates the form partial to use the correct field name.
My initial instinct was to write a regression test for this, but it
felt like opening a can of worms to test each input in the advanced
search form. I'd like the reviewer's input on this.
NO
NO

Fix name mismatch for fundingInformation

---

app/views/search/_form.html.erb
test/controllers/search_controller_test.rb
test/vcr_cassettes/advanced_all_spaces.yml

When the advanced search form is submitted, the full search term
is not retained if it includes a space.
https://mitlibraries.atlassian.net/browse/RDI-237
This wraps advanced search value attributes with quotations, so Rails
knows to retain the full param.
None.
NO
NO

Display complete input values in advanced search form

---

app/views/record/_record.html.erb

* As currently displayed, the full record view Source links could be
interpreted as going to the root of the source repository rather than
the individual record within the repository and thus might seem of
little value to end users.
* https://mitlibraries.atlassian.net/browse/RDI-240
* Provides a clearer link label to the Item record in the source
NO
NO

Updates link text for source on record pages

---

app/views/record/_record.html.erb

The record view does not join the content type field on a character,
so multiple content types are displayed in an unreadable format.
https://mitlibraries.atlassian.net/browse/RDI-242
This joins the content type field on a semicolon to render it
the same as the result view.
None.
NO
NO

Delimit content types in a readable format

---

app/helpers/facet_helper.rb
app/helpers/form_helper.rb
app/models/query_builder.rb
test/helpers/facet_helper_test.rb

NOTE: PR build has been updated to have RDI sources. You can see this in the PR build by:
* advanced search
* click search
* click dataset facet
* click still image facet
* confirm the result set is 9 records
* Being able to apply multiple values to a single facet type when
supported by the data model is important to be able to drill down
through results
* https://mitlibraries.atlassian.net/browse/RDI-241
* Updates the facet helper to support arrays of values instead of only
supporting strings
* Updated form helper to downcase sources to match applied facets for
source to avoid problems with duplicate values being applied
* moved contentType to …

Support multivalue facets

---

app/helpers/record_helper.rb
app/views/record/_record.html.erb
test/integration/error_resilience_test.rb
test/vcr_cassettes/alma_record_with_no_publication_date.yml

* Some records don't have publication date information (which is expected)
* https://mitlibraries.atlassian.net/browse/TIMX-108
* Adds nil protection for publication dates
* After handling the publication date nil, an error occurred for identifier not being present. I believe this is unexpected and is a result of incomplete Alma mappings in dev1 at this time. Handling nils for identifers seemed fine to include even if the data will likely all include at least one identifier per record.
Sample record to verify the change:
https://timdex-ui-pi-timx-108-p-nalqak.herokuapp.com/record/alma:9935254843506761
If you'd like to see the change locally, make sure you …

Support full records without pub_date or id

---

app/javascript/search_form.js
app/views/search/_form.html.erb

UXWS has requested that he simplify the language for the advanced search dropdown.
* https://mitlibraries.atlassian.net/browse/GDT-126
This updates the language as requested: "Advanced search" when the dropdown is closed, and "Close advanced search" when it's open.
Though it emerged from the GDT UI design work, this is a general enhancement that will apply to all TIMDEX UI apps.
NO
NO

Update advanced search language

---

docs/architecture-decisions/0002-extend-timdex-ui-for-gis-data.md

Why these changes are being introduced:
We plan to develop the GIS Data Tool UI as an extension of TIMDEX UI. We need to do so without disrupting the existing TIMDEX UI applications, while also planning for a potential future state in which those applications may include geospatial data.
* https://mitlibraries.atlassian.net/browse/GDT-123
How this addresses that need:
This adds an ADR to confirm our initial plan for the GDT UI.
Side effects of this change:
* We will be adding the `flipflop` gem in a future PR to manage a `gdt` feature flag.
* We will update the theme gem to add app names to headers (and potentially customize local navs).
* One decision in the ADR is contingent upon a decision we've yet to make, regarding whether we will want to display GIS results in …

Document initial architectural decisions related to GDT

---

.gitignore
Gemfile
Gemfile.lock
README.md
config/application.rb
config/environments/development.rb
config/environments/test.rb
config/features.rb
config/routes.rb
db/migrate/20240130222044_create_features.rb
db/schema.rb

We need a way to toggle GDT features, so we can manage non-GDT TIMDEX UI apps alongside it.
https://mitlibraries.atlassian.net/browse/GDT-157
This adds the `flipflop` gem and a GDT feature.
The `flipflop` gem doesn't appear to be very actively maintained these days. We'll want to keep an eye on that and, if it gets abandoned, consider switching to something like `flipper`.
YES
YES

Add GDT feature flag

---

app/controllers/search_controller.rb
app/views/search/_result_empty.html.erb
app/views/search/results.html.erb
test/controllers/search_controller_test.rb

When a search returns no results, the filter sidebar should be omitted and the 'no results' text should be larger. This change was requested as part of the GDT project, but it should apply to all TIMDEX UI apps.
* https://mitlibraries.atlassian.net/browse/GDT-133
Updates the 'no results' text and implements the requested styling changes. The filter logic changes a bit to hide the sidebar:
* In the search controller, empty aggregations are no longer extracted from the response.
* In the results view, a few conditionals have been added to hide the filter sidebar, omit the `layout1q3q` class from the results wrapper, and render the 'no results' message as a header rather than a list element.
* The results view is somewhat less elegant as a result of these changes.
* It felt strange to me to …

Update 'no results' partial

---

app/assets/stylesheets/partials/_filters.scss
app/helpers/filter_helper.rb
app/helpers/results_helper.rb
app/views/search/_filter.html.erb
app/views/search/_filter_empty.html.erb
app/views/search/results.html.erb
test/controllers/search_controller_test.rb
test/helpers/filter_helper_test.rb
test/helpers/results_helper_test.rb

The filter sidebar can become unwieldy, as all available filters are shown at all times.
https://mitlibraries.atlassian.net/browse/GDT-127
This restyles the filter sidebar as dropdown menus. In so doing, it also changes some behavior in the filter logic:
* Number of results is listed in the filter sidebar header.
* Applied filters are highlighted (previously, the 'applied' filter was added, but we hadn't done anything with it).
* Clicking an applied filter removes that filter (this replaces the previous removal mechanism, which removed all applied filters).
* Some tests have been updated to reflect the new logic.
* The sidebar elements have an animation that's tied to height. I've set the height to 200px and added a scroll-behavior rule if the number of filters available exceeds that …

Redesign filter sidebar

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_local_nav.scss
app/views/layouts/_site_nav.html.erb

The Geodata app requires links to GIS resources at MIT in the local nav. It also no longer requires the app name in the local nav, as GDT-125 moved this to the main header.
* https://mitlibraries.atlassian.net/browse/GDT-125
* https://mitlibraries.atlassian.net/browse/GDT-124
This updates the local nav as specified, provided the GDT feature is enabled.
We will likely want to remove the app name from the local nav in all our applications and use the new method provided by the theme gem instead. However, it is out of scope of this ticket (and project) to make that decision, so I've left it in for now.
issues (link to those issues in the Pull …

Redesign local nav for GDT

---

app/assets/stylesheets/partials/_panels.scss
app/assets/stylesheets/partials/_results.scss
app/assets/stylesheets/timdexui.scss
app/views/record/_sidebar.html.erb
app/views/search/results.html.erb
app/views/shared/_ask.html.erb

The main purpose of this PR is to add 'Ask GIS' links to all views except the index, as specified in [GDT-129](https://mitlibraries.atlassian.net/browse/GDT-129). This is toggled by a feature flag so it does not appear in other TIMDEX UI apps. (However, a similar feature may be useful for those apps, too.)
Secondarily, this removes some rules from `timdexui.scss`. This is unrelated to the ticket, but I noticed a comment in that file suggesting that those rules should be relocated, and this seemed like a good opportunity to do so.  Check the commit message for details, as two rulesets were removed altogether.
issues (link to those issues in the …

Add 'Ask GIS' panel and reorganize SCSS

---

app/assets/stylesheets/partials/_search.scss
app/views/basic_search/index.html.erb
app/views/layouts/_site_nav.html.erb
app/views/record/view.html.erb
app/views/search/_form.html.erb
app/views/search/results.html.erb
app/views/shared/_site_title.html.erb
app/views/static/_forms.html.erb

The GeoData visual design includes a heading at the top of each
page, along with some descriptive text.
https://mitlibraries.atlassian.net/browse/GDT-182
This adds the requested element as a partial, with conditional
copy for GDT versus non-GDT applications. It also moves the label text
to the `title` attribute, as the label is is now visually redundant but
may still be useful to screen reader users.
* The input label before form submit is now the same as the placeholder
text. This feels fine since screen readers might not read placeholder
text, but they do consistently rely on labels.
* The copy for non-GDT titles did not come from UXWS and is subject
to change.
all issues introduced by these changes have been …

Add site title partial

---

app/assets/stylesheets/partials/_pagination.scss
app/helpers/pagination_helper.rb
app/models/analyzer.rb
app/views/search/_pagination.html.erb
test/helpers/pagination_helper_test.rb
test/models/analyzer_test.rb

The GDT project has called for an update to how pagination is shown, across all instances of this app. The details are linked from the ticket below.
https://mitlibraries.atlassian.net/browse/gdt-172
* The visual display of the pagination links is changed, including which data points are included. Importantly, we are moving from a display that uses page numbers to one that uses result counts - so there are changes to the analyzer model to reflect this UI.
* We also improve the accessibility of the pagination element by using a nav element, and adding aria labels to make the screen reader output more coherent.
* Tests for both the helper and analyzer are also updated to expect the new markup.
* The analyzer test gets some additional assertions because of the calculations for the first and …

Update pagination according to mockupos

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_progress_bar.scss
app/javascript/application.js

* Our application may already be showing a progress indicator that comes with Rails, but the default rendering is very subtle (only three px high). We want to make this more prominent.
* https://mitlibraries.atlassian.net/browse/gdt-143
This makes two changes:
* Sets the threshold for showing the progress to bar to 200 milliseconds instead of the default 500. This will result in users seeing the progress bar more quickly while waiting for a slightly slow page load, which should give them greater assurance that the application is working on a response.
* Once shown, the progress bar is now 75 pixels tall, rather than 3. This is the height of the black navbar at the top of the page, which should make the progress bar much harder to miss when it appears.
This isn't a side effect, but an …

Make default progress indicator more prominent

---

config/schema/schema.json

This started as a speculative change, to confirm for myself that schemas were constrained in the way I suspected. After creating this Friday, and checking with @jazairi on Monday, this is no longer speculative.
The TIMDEX API has made some recent changes to its schema, which need to be reflected in this UI app as well.
** Relevant ticket(s):
n/a (Should there be a ticket for this?)
** How does this address that need:
This runs the console command in the UI app to update schema.json,
** Document any side effects to this change:
Some in-progress branches which have incorporated these changes on their own will need to be tweaked to remove the diff from their scopes.
all issues introduced by these changes have been …

Update schema definition after recent API changes

---

app/assets/stylesheets/application.css.scss
app/assets/stylesheets/partials/_filters.scss
app/assets/stylesheets/partials/_layouts.scss
app/javascript/filters.js
app/views/search/results.html.erb

The result filters are awkward on a mobile display, and may only be
needed for some users. Rather than having them display by default,
and take up space that is very precious, we want to only show a UI
control to expose them when needed.
https://mitlibraries.atlassian.net/browse/gdt-174
* This adds a button above the filters panel markup, and adds a few
classes to the existing markup at the top of the filters panel.
* With CSS, we hide the filters panel on the smallest screens using a
new hidden-sm class. This class is then toggled via javascript when
the user clicks on the UI button.
* The javascript is part of a new file - `app/javascript/filters.js` -
which is loaded by the filters partial.
* I'm not sure where best to add the .hidden-sm class to this codebase.
For now I'm adding it to …

Add toggle for filters on mobile UI

---

app/assets/stylesheets/partials/_panels.scss

Darcy suggested changing the color, spacing, and size of the chat icon.
* [GDT-129](https://mitlibraries.atlassian.net/browse/GDT-129)
This applies the suggested changes.
I'd originally intended to move the `view-md` and `view-lg` rules to the `layouts` partial, but opted against it since those are only used for this element. I'd be happy to make that change, though, if the reviewer feels otherwise.
NO
NO
[GDT-129]: https://mitlibraries.atlassian.net/browse/GDT-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

Address 'Ask Us' feedback from UXWS

---

app/assets/stylesheets/partials/_filters.scss

This request was made in UX review.
* [GDT-174](https://mitlibraries.atlassian.net/browse/GDT-174)
This adds 1rem padding to the filter toggle button.
None.
NO
NO
[GDT-174]: https://mitlibraries.atlassian.net/browse/GDT-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add padding to filter toggle button

---

app/assets/stylesheets/partials/_results.scss

The border causes the result container to shift 1px to the right on hover/focus.
* [GDT-237](https://mitlibraries.atlassian.net/browse/GDT-237)
* [GDT-215](https://mitlibraries.atlassian.net/browse/GDT-215)
This removes the border, but retains the background color change so there is still an indication of focus.
None.
I tried adding a 1px border all the way around, which also fixed the problem, but it didn't appear on the left for some reason. Rather than have an inconsistent border, it made sense to omit it altogether.
[GDT-237]: https://mitlibraries.atlassian.net/browse/GDT-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GDT-215]: …

Remove border from result hover/focus

---

app/assets/stylesheets/partials/_results.scss
app/assets/stylesheets/partials/_shared.scss
app/views/search/_highlights.html.erb

Why these changes are being introduced:
This was suggested by UXWS as a visual design improvement.
* [GDT-238](https://mitlibraries.atlassian.net/browse/GDT-238)
* [GDT-215](https://mitlibraries.atlassian.net/browse/GDT-215)
How this addresses that need:
This changes the result titles, authors, and highlights heading to the suggested sizes.
Side effects of this change:
None.
Though it's not a new issue, running WAVE this time reminded me that it gets confused by the authors list, thinking it should be a heading. Most likely, that section *should* have a heading; it should probably also be an unordered list rather than a series of `a` tags within a `p` tag. I'm not sure whether this is the sort of thing that should be ticketed at this point, or if it should just wait …

Reduce size and overlap of result titles

---

app/assets/stylesheets/partials/_search.scss
app/javascript/search_form.js
app/views/search/_form.html.erb

Note to reviewer: this has not yet passed QA. I was hoping to complete UXWS review before merging, but I'd like to start working on advanced search form updates that are likely to cause merge conflicts with this PR.
This is in response to a UX review of location-based search.
* [GDT-136](https://mitlibraries.atlassian.net/browse/GDT-136)
* Removes top margin from all `details` elements except the first.
* Bolds labels.
* Moves placeholder text to description `span` elements and changes "e.g." to "Ex:".
* Changes language for distance description/hint.
* Changes summary labels for geobox and geodistance.
* Removes red asterisks as indicators of required classes, and instead adds a `p` tag indicating as much below each `legend`.
None.
[our …

Address UX feedback on location-based search form

---

app/assets/stylesheets/partials/_shared.scss

This is a follow-on request for GDT-238 that Darcy suggested and
I enthusiastically support.
* [GDT-238](https://mitlibraries.atlassian.net/browse/GDT-238)
This reduces the font size for authors to 1.6rem.
While reviewing this, Darcy noticed a bug in iOS where the second
line of an ordered list element appears to have top padding. We
opened [GDT-246](https://mitlibraries.atlassian.net/browse/GDT-246)
to explore this further.
Ignore the many force-pushes and deploys on this PR. I was using the PR builds in draft mode to check potential solutions to the aforementioned iOS bug.
[GDT-238]: https://mitlibraries.atlassian.net/browse/GDT-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Adjust font size for authors element

---

app/helpers/filter_helper.rb
app/views/search/_filter.html.erb
app/views/search/_search_summary.html.erb
test/controllers/search_controller_test.rb
test/helpers/filter_helper_test.rb

GDT needs to provide users the option to toggle between MIT and non-MIT results. The source filter is reasonable solution for MVP, but the current values are not intuitively named.
* [GDT-245](https://mitlibraries.atlassian.net/browse/GDT-245)
This adds a `gdt_sources` method in the filter helper that is a lookup hash that translates the two GDT sources. If the GDT feature is enabled, then source values are translated to the desired labels in the filter panel and sidebar.
* There was a lingering `to_sym` coercion in the filter partial. I removed it, as it is no longer need after last month's filter redesign. Its removal is unrelated to this change.
* This was a bit tricky to test. Because geo search is currently siloed, I can't confirm that non-GDT sources remain unaffected when the GDT …

Relabel source values for GDT

---

app/assets/stylesheets/partials/_results.scss
app/helpers/search_helper.rb
app/views/search/_result_geo.html.erb
test/controllers/search_controller_test.rb
test/helpers/search_helper_test.rb

This responds to UX feedback on GDT-130 (result view for GDT).
* [GDT-130](https://mitlibraries.atlassian.net/browse/GDT-130)
This removes result padding in smaller viewports, moves result markers outside of the titles, changes full record link hover/focus color to blue, and removes the visited styling for full record links.
The visited styling remains for 'View online' links in other TIMDEX UI apps, as these are outlinks to the source record. The GDT links go to the full record, which is already indicated as visited in the title link, so it doesn't feel critical to add visited styling to the button as well.
[GDT-248](https://mitlibraries.atlassian.net/browse/GDT-248) has been opened to address some feedback on the result highlight labels.
N/A
(not just this pull …

Address UX feedback on GDT result view

---

app/assets/stylesheets/partials/_results.scss
app/helpers/results_helper.rb
app/views/search/results.html.erb
test/helpers/results_helper_test.rb

We will be moving the filter sidebar further down the tab order, so screen reader users would not reach the number of search results until they reach the end of the results. This foregrounds that context, both for blind/low-vision and sighted users.
* [GDT-235](https://mitlibraries.atlassian.net/browse/GDT-235)
This moves the number of results returned to the top of the results container, making it the first focusable element when a screen reader user skips to results.
The results ID moves up one level in the DOM to account for the new heading.
N/A
[GDT-235]: https://mitlibraries.atlassian.net/browse/GDT-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Move results context from filter sidebar to results container

---

app/helpers/record_helper.rb
app/views/record/_access_button.html.erb
app/views/record/_record_geo.html.erb
app/views/shared/_geo_data_info.html.erb
test/helpers/record_helper_test.rb

The "access to files" values have been changed in the data mapping
layer. We need to make a corresponding change in a few partials
where the value of that field is a rendering condition.
* [GDT-252](https://mitlibraries.atlassian.net/browse/GDT-252)
This updates the values as needed in the access_button, record_geo, and
geo_data_info partials, as well as the access_type helper method.
It was a bit tricky to wrangle and update all of these hardcoded values.
Though they are unlikely to change again, this is something that
we may want to consider refactoring.
To confirm the changes, check a full record for each of the three access types. The download buttons should contain the following text, based on the access type:
* `MIT authentication required`: "Download geodata files `fa-lock icon` …

Update access type values

---

app/views/search/_filter.html.erb
test/controllers/search_controller_test.rb

When introducing the helper method to rename GDT source filter values, we inadvertently removed all filter values for non-GDT apps. This is hilarious, but not very usable.
N/A
This adds to the filter partial an `else` clause that renders the term key if GDT is not enabled.
Users will know what filters they are applying.
Successful application and removal (and visibility) of filters should be confirmed with and without the GDT feature flag.

Render filter value names in non-GDT contexts

---

app/assets/stylesheets/partials/_filters.scss

The SCSS for the filter names in the sidebar doesn't work exactly the way we intend it to. When an applied filter is in focus, the font color is black; it should be white to contrast with the background.
Discovered while working on [GDT-232](https://mitlibraries.atlassian.net/browse/GDT-232), but otherwise unrelated to that ticket.
This updates the SCSS so that applied filters are white on focus and hover.
None.
Confirm that, while a filter is in focus, its color is white, not black.
[GDT-232]: https://mitlibraries.atlassian.net/browse/GDT-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix bug in filter sidebar SCSS

---

test/controllers/record_controller_test.rb

There were three record controller tests that had to be skipped due to a data reload that was in process. That reload, which was related to the access type values, is now complete, and the corresponding UI code has been updated, so these tests will pass again.
* [GDT-252](https://mitlibraries.atlassian.net/browse/GDT-252)
This removes the skip statements from the tests in question, so they will run again.
None.
N/A.
[GDT-252]: https://mitlibraries.atlassian.net/browse/GDT-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove skips from record controller tests

---

app/helpers/search_helper.rb
app/views/search/_highlights.html.erb
test/helpers/search_helper_test.rb

The OpenSearch highlight field collects matched field names as-is, so for nested fields we get names like `subjects.value`.
* [GDT-248](https://mitlibraries.atlassian.net/browse/GDT-248)
This adds a helper method to parse matched field names.
None.
The helper method first calls `underscore` then `humanize`, so field names with multiple words should appear like "Alternate title" and one-word field names should appear like "Format."
[GDT-248]: https://mitlibraries.atlassian.net/browse/GDT-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Make result highlight field names more human-readable

---

app/helpers/application_helper.rb
app/views/basic_search/index.html.erb
app/views/record/view.html.erb
app/views/search/results.html.erb
test/helpers/application_helper_test.rb

Every view currently has the same generic title content. It's common practice in discovery applications to include context about the current query in the page title, so users can see these pertinent details in a given tab or bookmark.
* [GDT-234](https://mitlibraries.atlassian.net/browse/GDT-234)
This adds helper methods to construct page titles for the following views:
* `basic_search/index`: "Search `PLATFORM_NAME` | MIT Libraries"
* `record/view`: "`record['title']` | `PLATFORM_NAME` | MIT Libraries"
* `results`: "`params from enhanced query` | `PLATFORM_NAME` | MIT Libraries"
If the query/title preview string exceeds a configurable character limit (defaults to 50 for results and 25 for record), the string is truncated with an ellipsis.
None.
I'm waiting to hear from Darcy if she wants …

Improve page titles

---

app/javascript/application.js
app/views/layouts/_head.html.erb

[Turbolinks is no longer actively developed](https://www.honeybadger.io/blog/hb-turbolinks-to-turbo/). We should switch to Turbo for our progress bar customization.
* [GDT-289](https://mitlibraries.atlassian.net/browse/GDT-289)
This migrates our use of Turbolinks to (currently limited to the progress bar) to Turbo.
A small change, recommended in the blog post linked above, has been made to the `stylesheet_link_tag` element in our custom head (adding `media: all`).
Confirm in the PR build (or locally):
* No errors related to Turbolinks appear in the console; and
* Links are still preloaded (the easiest way to test this is by hovering over filter links and checking in the Rails logger if requests were made).
[GDT-289]: …

Switch from Turbolinks to Turbo for progress bar

---

app/views/layouts/_head.html.erb

Why these changes are being introduced:
It’s a known issue that the out-of-the-box Matomo tracking code does not work with Turbo, but we want to continue using Turbo because it's great.
* [GDT-289](https://mitlibraries.atlassian.net/browse/GDT-289)
How this addresses that need:
This adds a JS snippet to the tracking code, based on Matomo's instructions for tracking SPA's, that sends an event to Matomo when Turbo loads a page. See [this GitHub issue](https://github.com/turbolinks/turbolinks/issues/436) for details.
Side effects of this change:
We should add this change to the theme gem if it works for apps that are not using Turbo. (It should, but I haven't confirmed it.)
To confirm the changes, you can deploy this to GeoData staging and confirm that pageviews and …

Add turbo:load event listener to Matomo code

---

app/views/shared/_site_title.html.erb

The current site title is not entirely accurate.
* [GDT-291](https://mitlibraries.atlassian.net/browse/GDT-291)
This updates the site title as requested.
None.
The new h1 and subtitle should read:
```
Search for Geospatial/GIS data
Find GIS data held at MIT and other institutions
```
[GDT-291]: https://mitlibraries.atlassian.net/browse/GDT-291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update site title based on stakeholder feedback

---

app/assets/stylesheets/partials/_search.scss
app/views/search/_form.html.erb

Now that we have several input fields in the search form, it would be helpful to have a button that can clear everything in the form.
* [GDT-244](https://mitlibraries.atlassian.net/browse/GDT-244)
This adds to the form an `a` tag, styled as a button, that links to the root route.
* In order to accommodate both buttons next to the basic search input, the form breaks at a medium screen width rather than a small one.
* Darcy has indicated that we may need to refine this as additional use cases emerge.
N/A
[GDT-244]: https://mitlibraries.atlassian.net/browse/GDT-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add affordance to clear search terms

---

app/views/layouts/_skip_links.html.erb

Kate and Rich from DAS advised us that skip links are primarily for sighted users navigating with a keyboard, and it's very unusual to find more than one skip link. To that end, we've decided to simplify the skip links.
* [GDT-280](https://mitlibraries.atlassian.net/browse/GDT-280)
* All skip links now have the same conventional text: 'skip to main content'.
* On the results view, there is one skip link that goes to the results list.
* On the full record view, there is one skip link that goes to the top of the record.
* On all other views (i.e., the landing page), there is one skip link that goes to the first input in the search form (keyword search).
We may need to revisit this after a11y testing to confirm that the skip links are useful.
Based on the new info we got from DAS, I think …

Remove additional skip links

---

app/assets/stylesheets/partials/_search.scss
app/views/search/_form.html.erb

UXWS changed their mind on this feature. They believe it's likely to be confusing.
* [GDT-244](https://mitlibraries.atlassian.net/browse/GDT-244)
This removes the 'clear' button from the search form and resets the CSS accordingly.
None.
Form display should now be identical to GeoData prod.
[GDT-244]: https://mitlibraries.atlassian.net/browse/GDT-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove affordance to clear search terms

---

app/views/basic_search/index.html.erb
app/views/layouts/application.html.erb
app/views/record/_record.html.erb
app/views/record/_record_empty.html.erb
app/views/record/_record_geo.html.erb
app/views/record/_sidebar.html.erb
app/views/search/_form.html.erb
app/views/search/_search_summary.html.erb
app/views/search/results.html.erb
app/views/shared/_ask.html.erb
app/views/shared/_error.html.erb
test/controllers/record_controller_test.rb

It was suggested in a recent meeting with DAS that the best way to make a page navigable to screen reader users is by using semantic HTML and ARIA roles.
* [GDT-279](https://mitlibraries.atlassian.net/browse/GDT-279)
This attempts to make better use of semantic HTML elements and ARIA roles throughout our views.
This should be considered a first iteration, as we have not undergone a11y review yet. I tried to use a light touch due to my lack of familiarity with ARIA, but we may learn that additional context would be useful.
N/A
[GDT-279]: https://mitlibraries.atlassian.net/browse/GDT-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor markup to provide more semantic meaning

---

app/views/search/_highlights.html.erb
app/views/search/_result.html.erb
app/views/search/_result_geo.html.erb
app/views/shared/_ask.html.erb
app/views/shared/_site_title.html.erb

We currently have two issues with our heading structure:
1. Multiple `h1` tags, which is not recommended.
2. Each result title is an `h2`, which is no longer semantically correct as the results list now has an `h2` tag at the top.
* [GDT-293](https://mitlibraries.atlassian.net/browse/GDT-293)
This changes the `site_title` heading from an `h1` to an `h2`, and updates results to use an `h3` heading for the record title, and an `h4` heading for the search highlights section.
The `h1` in the header seems adequate for now, but we might want to iterate on this further if DAS feels otherwise during accessibility testing.
N/A
[GDT-293]: https://mitlibraries.atlassian.net/browse/GDT-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …

Restructure headings

---

app/javascript/search_form.js
app/views/search/_form.html.erb

The change in label for these accordions when open (e.g., 'Advanced search' to 'Close advanced search') is unnecessary and confused some usability test participants.
The 'Advanced search' menu was also unused without prompting in usuability testing. UXWS has suggested relabeling it for clarity.
* [GDT-301](https://mitlibraries.atlassian.net/browse/GDT-301)
This relabels the accordion menus as suggested by UXWS.
None.
N/A.
[GDT-301]: https://mitlibraries.atlassian.net/browse/GDT-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Relabel geospatial and advanced search accordion menus

---

app/assets/stylesheets/partials/_panels.scss
app/helpers/application_helper.rb
app/helpers/search_helper.rb
app/views/search/_search_summary.html.erb
test/controllers/search_controller_geo_test.rb
test/controllers/search_controller_test.rb
test/helpers/application_helper_test.rb
test/helpers/search_helper_test.rb
test/vcr_cassettes/advanced_all.yml
test/vcr_cassettes/advanced_keyword_asdf.yml

We had been leaning on the search form to remind users of the current search params, but this is not always reliable (e.g., if a input is cleared without executing a new search).
* [GDT-285](https://mitlibraries.atlassian.net/browse/GDT-285)
This displays applied search terms in the summary panel where we show applied filters.
Two skipped tests, which confirmed an earlier iteration of this feature, have been reintroduced.
It may be useful to apply some filters to see what that looks like alongside the applied search terms. (I separated them with a border, which I don't love aesthetically, but it probably adds visual clarity.)
[GDT-285]: https://mitlibraries.atlassian.net/browse/GDT-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Display search terms in summary panel

---

app/views/search/_highlights.html.erb

Usability testing indicated that the current search highlights heading may be confusing to some users.
* [GDT-305](https://mitlibraries.atlassian.net/browse/GDT-305)
This relabels the heading as suggested by UXWS.
None.
N/A
[GDT-305]: https://mitlibraries.atlassian.net/browse/GDT-305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Relabel search highlights heading

---

app/assets/stylesheets/partials/_panels.scss
app/views/search/_search_summary.html.erb

The current CSS rules for the search summary panel results in an unintended top margin if geospatial/advanced search terms are entered without a keyword.
N/A
This puts the top margin for applied terms on the `ul` elements instead of the `li` elements. It also adjusts the margin to match the others.
N/A
This is unticketed because I noticed it while working on an unrelated ticket.

Fix spacing for search summary panel

---

README.md
app/helpers/results_helper.rb
app/views/search/results.html.erb
test/controllers/search_controller_test.rb

* Our experimental fact panels need to be disabled by default now that a version of this UI is moving to production
* https://mitlibraries.atlassian.net/browse/GDT-313
* Adds a configuration option that takes a comma separated list of fact panels that should be enabled.
* If a fact panel is enabled and there is a a detected fact of that type a fact panel will display as it did previously. If a fact is detected of a type in which no fact panel has been enabled, we do not display a fact panel.
* If no fact panels are enabled, we don't check for specific fact panels to determine if they should be enabled.
After discussion with the team, we chose not to use …

Fact panels controlled via configuration

---

app/helpers/record_helper.rb
app/views/record/_record_geo.html.erb
test/helpers/record_helper_test.rb

The same subject value can appear twice in the full record view. In some cases, this is because the value appears in the record for different subject kinds. However, it's also entirely possible for the same kind/value pair to appear multiple times [in the same record](https://timdex-ui-prod.herokuapp.com/record/alma:990005961340106761), so merely including the subject kinds as we do in other TIMDEX UI apps does not solve this problem.
* [GDT-297](https://mitlibraries.atlassian.net/browse/GDT-297)
This adds a `deduplicate_subjects` method that calls `uniq` on a record's subject values (within a given term and across all term), then returns the deduplicated, two-dimensional array of values.
Case is ignored to manage known instances of the same subject value appearing as capitalized and …

Deduplicate subject values in GDT

---

app/assets/stylesheets/partials/_filters.scss
app/assets/stylesheets/partials/_panels.scss
app/assets/stylesheets/partials/_results.scss
app/assets/stylesheets/partials/_search.scss
app/views/search/_form.html.erb

Accessibility testing revealed that the search button is difficult for screen reader users to locate, and that the `title` attribute for the keyword search input is not useful.
* [GDT-318](https://mitlibraries.atlassian.net/browse/GDT-318)
This changes the keyword `title` to 'keyword anywhere' and moves the search button to the bottom of the form, after all of the advanced search dropdowns. It also updates some corresponding CSS, including removing the `border-radius` override for the `btn` class, so the search button looks more like a button.
Fixed margin/padding for results summary panel and mobile filter toggle. (This is unrelated to this change, but I noticed while testing out the changes that the spacing looked odd.)
UXWS will do this as part of QA, but it may be worth checking that …

Improve accessibility of search form

---

app/assets/stylesheets/partials/_record.scss
app/views/record/_access_buttons.html.erb
app/views/record/_record_geo.html.erb
app/views/record/_sidebar.html.erb

The metadata download link appears at the end of the full record with no heading. This makes it look like part of the last full record heading (usually 'Languages').
A related issue is that the access link in the sidebar has no heading. We have an `aria-label` that describes this section for screen reader users, but for sighted users, this section lacks context.
As part of their accessibility review, DAS has recommended moving the metadata download link to the same section as the access link.
* [GDT-319](https://mitlibraries.atlassian.net/browse/GDT-319)
This moves the download link below the access link in the sidebar, and adds a heading to that section.
While working on this, I noticed that the fact panel markup needs some work to be semantically meaningful. I haven't touched that in …

Consolidate full record access links in sidebar

---

app/assets/stylesheets/partials/_record.scss
app/views/record/_sidebar.html.erb

UXWS has requested some changes to the access link sidebar (and the full record view more broadly).
* [GDT-319](https://mitlibraries.atlassian.net/browse/GDT-319)
* Changes aria-label for the sidebar;
* Updates heading typography to match the filter sidebar heading; and
* Adds top margin to the full record.
None.
UXWS will confirm that it looks the way they want it to, so this review is just to confirm the HTML/CSS changes are valid.
[GDT-319]: https://mitlibraries.atlassian.net/browse/GDT-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Implement UX feedback on access link sidebar

---

app/assets/stylesheets/partials/_results.scss

The result list does not have a sufficient left margin to
accommodate list markers that are more than one digit. Because
of this, markers for results further down in the list are
truncated.
This issue exists on smaller viewports only. Larger viewports
have enough space for markers up to five digits. (This is the
maximum, in our case.)
* [GDT-314](https://mitlibraries.atlassian.net/browse/GDT-314)
This adds a left margin on smaller viewports to accommodate
4-digit result markers, and removes the result padding to provide
more room for text flow.
* The margin is somewhat excessive for 1- or 2-digit numbers, but
it seems like a reasonable tradeoff for now.
* The leading digit of 5-digit numbers is still truncated. This only
affects one possible result, and it's unlikely that a user would get …

Accommodate multi-digit list markers

---

app/assets/stylesheets/partials/_results.scss
app/assets/stylesheets/partials/_shared.scss
app/views/record/_record_geo.html.erb
app/views/search/_result.html.erb
app/views/search/_result_geo.html.erb
app/views/shared/_contributors.html.erb

Authors are currently rendered within a `p` tag. This is not very semantically meaningful.
* [GDT-284](https://mitlibraries.atlassian.net/browse/GDT-284)
This refactors the contributors section to a partial and renders contributors as an unordered list. It is the same changeset that was introduced in #191, but without displaying the contributor type, which UXWS has deemed unnecessary at this time.
None.
N/A
[GDT-284]: https://mitlibraries.atlassian.net/browse/GDT-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Improve markup for contributors

---

app/javascript/search_form.js
app/views/search/_form.html.erb
app/views/shared/_site_title.html.erb

DAS has informed us that it is bad practice to use both `required` and `aria-required`. They also suggested that we add an `aria-describedby` to the keyword input that links to the `p` tag below the site title.
* [GDT-327](https://mitlibraries.atlassian.net/browse/GDT-327)
This removes the redundant `aria-required` attributes and makes the suggested labeling change for the keyword input.
The labeling piece only affects GDT, as non-GDT apps don't currently use the `site_title` partial. This feels acceptable, because the keyword input is more clearly labeled in other TIMDEX UI applications.
Confirm that required fields are still required (i.e., built-in form validations fire when they are empty).
[GDT-327]: …

Fix form required attributes redundancy and keyword input description

---

app/assets/stylesheets/partials/_results.scss
app/views/search/_result.html.erb
app/views/search/_result_geo.html.erb

SwiftUI/iOS has some unusual behavior for list markers. It adds line height to them, such that when we increase the font size for a marker, the line height is dramatically increased. This is particularly visible when the text next to the marker wraps, which is common for TIMDEX UI record titles.
* [GDT-246](https://mitlibraries.atlassian.net/browse/GDT-246)
This implements a CSS workaround. First, we reset the line height to 0 on `.result`, enforcing no line height for markers. Then, we add a div to wrap the rest of the result (`.result-content`), with a rule that sets the line height to 1.2.
I don't forsee any, but it's a pretty ugly workaround to accommodate a minor bug in a weird OS.
This will get UXWS review, but if the code reviewer would like to do QA as well, it would be useful to …

Fix iOS text wrap bug

---

app/views/record/view.html.erb
app/views/search/results.html.erb

* It doesn't make sense to have search engines index and follow links from our own results and record pages
* https://mitlibraries.atlassian.net/browse/TIMX-476
* adds meta robots tag with noindex, nofollow rules
E.g., if the PR includes updated dependencies and/or data
migration, or how to confirm the feature is working.

Adds crawler directives to result and record pages

---

.env.test
README.md
app/models/normalize_primo_record.rb
app/models/normalize_primo_results.rb
app/models/primo_search.rb
test/fixtures/primo/full_record.json
test/fixtures/primo/minimal_record.json
test/models/normalize_primo_record_test.rb
test/models/normalize_primo_results_test.rb
test/models/primo_search_test.rb
test/test_helper.rb
test/vcr_cassettes/primo_search_error.yml
test/vcr_cassettes/primo_search_success.yml

The first iteration of USE UI will include the
ability to toggle between Ex Libris CDI and
TIMDEX results.
* [USE-30](https://mitlibraries.atlassian.net/browse/USE-30)
This adds a Primo Search model that calls the
Primo Search API, and a Normalize Primo model that parses the each result and returns a normalized
record.
* For better or worse, much of the normalization code has been repurposed from Bento. This felt
acceptable as we do not anticipate this to be a
long-term solution.
* While working on this, I noticed that most of the TIMDEX normalization logic happens in the
views. It would be better to move this to
a normalization model, as we've done here with
Primo. I opened [USE-73](https://mitlibraries.atlassian.net/browse/USE-73) to address this.
* It's not technically a side effect of …

Add models for Primo Search API integration
